export const configRouter = {
    home: "/",
    login: "/login",
    signUp: "/signup",
    forgetPassword: "/forget-password",
    resetPassword: "/reset-password",
    // admin router
    dashboardAdmin: "/admin/dashboard",
    products: "/admin/products",
    categorys: "/admin/categorys",
    ourStaff: "/admin/our-staff",
    orders: "/admin/orders",
    coupons: "/admin/coupons",
    marketing: "/admin/marketing",
    customPage: "/admin/custom-page",
    profileAdmin: "/admin/profile",
    addProduct: "/admin/add-product",
    orderDetail: "/admin/orders/:id",
    addMarketting: "/admin/add-campaign",
    editMarketting: "/admin/edit-campaign/:id",
    editProduct: "/admin/edit-product/:id",
    reviewProduct: "/admin/product/reviews/:id",
    branchs: "/admin/branchs",
    addBranchs: "/admin/add-branch",
    editBranchs: "/admin/edit-branch/:id",
    album: "/admin/albums",
    profile: "/admin/profile",
    users: "/admin/users",
    // add type coupon
    couponShipping: "/admin/add-coupons/shipping",
    couponAmountOfProduct: "/admin/add-coupons/amount-off-product",
    couponAmountOfOrder: "/admin/add-coupons/amount-off-order",
    couponBuyXGetY: "/admin/add-coupons/buy-x-get-y",
    // edit type coupon
    couponShippingEdit: "/admin/edit-coupons/shipping/:id",
    couponAmountOfProductEdit: "/admin/edit-coupons/amount-off-product/:id",
    couponAmountOfOrderEdit: "/admin/edit-coupons/amount-off-order/:id",
    couponBuyXGetYEdit: "/admin/edit-coupons/buy-x-get-y/:id",
};
